sudo: required
language: python

python:
    - "3.5"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install texlive-latex-base
    - sudo apt-get install texlive-latex-extra

script:
    - make
